apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus
      version: '11.16.9'
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 1m
  values:
    pushgateway:
      enabled: false