apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/mccricardo/gitops-flux-helm
  name: gitops-flux-helm
  description: Gitops Flux Helm demo
  tags:
    - gitops
spec:
  type: service
  lifecycle: production
  owner: user:guest
